### PR TITLE
Add Echidna PBT-fuzzer

### PR DESCRIPTION
**Pull request by agroce**

### CODE REVIEW

**Comment by jmid** [comment]
Thanks! Having studied the DeepState description some more, it is not clear that DeepState (or Echidna) support Integrated Shrinking as described, e.g., by MacIver https://hypothesis.works/articles/integrated-shrinking/
so I fear we are misunderstanding each other. Allow me to elaborate:
Many PBT-frameworks let you write "custom generators" of input test-data satisfying some invariants:
 - even numbers (MacIver's example)
 - sorted lists
 - C programs free of undefined behaviour (CSmith)
 - type-correct OCaml programs https://github.com/jmid/efftester
 - WebAssembly passing stack validation https://github.com/jmid/wasm-prop-tester
 - ...

In either of these cases it is undesirable to reduce a counterexample (testcase) satisfying the invariant into a smaller/simpler one that doesn't, e.g., reducing a failing even number `6` into `1` (MacIver again). One can then write an accompanying "custom reducer/shrinker" such as C-reduce. This can be quite some effort. I've written such shrinkers myself for the latter two above.
A "modern school of PBT frameworks" (Hypothesis, Hedgehog, ...) follow a 'write-a-generator, get-a-shrinker-for-free' approach, where the shrinker is aware of the generator that produced the input data and can thereby carefully maintain any such invariants (parity, sortedness, ...). This is very nice from a developer's perspective (less work) and for positive testing when we want to test on "input according to a spec". Technically it is realized in different ways (Rose trees, Hypothesis' tree of random choices, ...).

For negative testing modern fuzzers (AFL, libFuzzer, DeepState, ...) seriously rock - witnessed by the impressive amount of bugs they have found. However, as I understand DeepState (and Echidna), their reducers are not "generator aware" in this sense (perhaps theft's auto-shrinker isn't either?). As I understand the documentation https://github.com/trailofbits/deepstate/blob/master/docs/basic_usage.md#test-case-reduction one should however be able to reduce to a simpler input, e.g., with the same coverage or failing the same assertion - which may go some of the way (distinguishing `assertion failure: input is not sorted`), but for something more complex like C-reduce I expect no assertions are triggered to help avoid reducing a well-defined C program into one with undefined behaviour (sanitizers could perhaps help here). 

This seems to me as a deeper difference in the approaches despite them having several similarities. Do you agree?

If you agree that DeepState and Echidna don't support integrated shrinking in the above sense:
I'm not sure how to best distill the above into a table that was originally just intended to highlighting QuickCheck-style feature differences, without making the PBT-fuzzers looking unfairly bad on parameters they were not designed for. I was thinking of adding
- a second footnote to elaborate a bit on reduction criteria, e.g, "simplifying to same assertion failures"
- a 'Coverage'-column to distinguish the "classic blackbox-PBT frameworks" from the graybox/coverage-driven ones. Then I could also add the Crowbar QuickCheck-AFL hybrid: https://github.com/stedolan/crowbar

However I'm open to suggestions that can make things clearer (and us all wiser) 😀

**Comment by agroce** [comment]
Hmm, yeah, this is tricky.  @drmaciver and I have talked a lot about shrinking over the years!

In DeepState and Echidna, custom generators are going to be implemented in the source language, in some sense, built on the primitives generators of the property-based tool.  In DeepState, an evens-only generator would either generate an int in half the range and double it, or generate an arbitrary int then use an ASSUME to throw out odds.  In either case, a shrink is guaranteed to not change any of this, since it operates (like, at a very high level of abstraction, Hypothesis) on the "raw" data and then the DeepState "parser/scanner" turns that into some actual test data, and it always has to ensure an arbitrary stream stays valid.  I _think_ this is probably a kind of "integrated shrinking" in that if you write a generator in the natural way, it'll shrink fine without any effort on your part, getting transformed automatically.  The details are different than Hypothesis, but I _think_ at a high level the "if you've defined a validity notion, you stay valid" invariant is kept, without any user effort. That seems to me to be the essence?

Echidna's operating differently, but it also is never going to lose validity of a test during shrink, or require any custom effort.  If you wrote a "custom generator" it would be some solidity function that maps input values into new values, since the generation in Echidna is entirely over Solidity types that can be input into a contract.  A Solidity 'require' can work like an assume and easily maintain validity, again.  The internals are a lot more different than what Hypothesis does than with DeepState (DeepState's reducer was written during a time David and I were talking a lot about reducers, for one thing).

I think there's a difference here, and how people write/use custom generators is a little different in these two tools, but I think at least DeepState may be doing "integrated shrinking" in the full sense.

**Comment by agroce** [comment]
So in DeepState, a "sorted list generator" assuming a LinkedList type exists might look like:

```
LinkedList* generateSortedList(size_t max_len) {
   LinkedList* ll = newLinkedList();  // assume this mallocs the list
   size_t length = DeepState_UIntInRange(0, max_len);
   int min_val = DeepState_Int();
   for (size_t i = 0; i < length; i++) {
       int v = DeepState_IntInRange(min_val, MAX_INT);
       min_val = v;
       ll->insert(v);
   }
   return ll;
}
```

and if you write this and use it in your tests, DeepState won't require you to do any additional work to get shrinking that works for that, and preserves the "returns sorted linked lists" aspect.  The implementation of ..InRange handles it by knowing how to map an arbitrary bytestream into the data needed.

The question of assertions/property to preserve in a shrink is orthogonal.  You could have integrated shrinking with user-defined predicates to preserve, in case you want to say "reduce this to any old failure" or "reduce this to a failure with a signature (exception raised, string output, etc.)". I don't remember how Hypothesis lets you control that kind of thing.

If you want C-Reduce-level-of-power validity, of course, it will be very expensive, but in theory in DeepState you can shrink preserving arbitrary validity properties, though for arbitrary validity properties you also may get a strategy no better than guess-and-check (this has to be the case for Hypothesis, too, just by a kind of shrinking variant of Rice's theorem, I'd guess)...

**Comment by agroce** [comment]
I think basically DeepState's point is to, by doing "approximately Hypothesis-like bytestream handling" (though again these are similar only at a pretty high conceptual level) to transform modern fuzzers into true PBT tools.  afl's really just a source of bytes, and its lack of understanding of anything other than bytes and crashes is mediated away by DeepState.

**Comment by agroce** [comment]
I want to add my TSTL tool, also, but _I_ got stuck on the question of whether I consider it to have integrated shrinking, since it is such a different paradigm.  :)

**Comment by agroce** [comment]
Maybe @drmaciver can weigh in:  David, do you think TSTL has "integrated shrinking" or not?

On the one hand, a test is never reduced to a less-valid test, and via guards you can have arbitrary validity constraints.  OTOH, the concept of a custom generator is so different it's a little odd.  I guess from a user perspective, I'd say you have integrated shrinking in a tool if

1) it can shrink any test you give it
2) tests can include arbitrary validity conditions
3) those conditions are always respected, no reducing a "give me an odd number" with counterexample 3 to 2

TSTL seems to meet that, though in TSTL it's trivial, since a test is a sequence of finite selections from a finite domain of enabled actions, and validity is just "in the guards"

**Comment by agroce** [comment]
Oh and of course:

4.  you get this for free, no having to write a custom shrinker!

**Comment by agroce** [comment]
Something like pure Zeller ddmin, without some added way to test validity, basically does not do this, though if your validity-respecting is done via your tests "always" being valid via some method of mapping arbitrary raw data into valid data, it can

**Comment by agroce** [comment]
In either case, I'll add a request to add TSTL

| [TSTL](https://github.com/agroce/tstl)                   | Python (API sequences)             | :heavy_check_mark: | :heavy_check_mark:    |               |               |

with the check mark actual value TBD pending this discussion resolving :)

**Comment by DRMacIver** [comment]
> Maybe @DRMacIver can weigh in: David, do you think TSTL has "integrated shrinking" or not?

I think this is a hard question to answer, because it feels like a bit of a category error. The answer isn't really yes or no so much as "this question doesn't seem relevant". TSTL isn't really the sort of object to which the term "integrated shrinking" was intended to apply.

I think it's fair to say that TSTL has none of the problems that a property-based testing library without integrated shrinking would have, but it does this by not having most of them in the first place because it uses a simpler data model.

It's probably more accurate to say in this terminology that TSTL is a single dedicated generator, reducer, and validity oracle for TSTL programs - the shrinking is "external" but that doesn't matter because you can't write new generators, so you never need to write a new shrinker.

(This is something of a dodge because one could kinda make the same argument for Hypothesis, but I think it's more true for TSTL than it is for Hypothesis because of the way TSTL makes building up new values more explicitly about combining sequences of actions)

DeepState (I don't know about echidna) on the other hand seems to clearly have integrated shrinking, in that it uses roughly the same shrinking model as Hypothesis, albeit with a less sophisticated shrinker, right?

**Comment by jmid** [comment]
OK, thanks for sharing your thoughts - both of you!

> If you want C-Reduce-level-of-power validity, of course, it will be very expensive, but in theory in DeepState you can shrink preserving arbitrary validity properties, though for arbitrary validity properties you also may get a strategy no better than guess-and-check (this has to be the case for Hypothesis, too, just by a kind of shrinking variant of Rice's theorem, I'd guess)...

Two things spring to mind here:
- Hypothesis is doing something more clever then guess-and-check here (described in @DRMacIver's ECOOP paper) and similarly for Hedgehog. In essense should one write a CSmith clone using any of these, they will reduce to "a smaller testcase program also producable by the same generator". Pro: no surprises or need for validity oracle - Con: not necessarily a "globally minimal" reduced example.
- Your point about Rice's theorem is well taken. I think it also applies to generators - even though that is strictly speaking not a 'decision problem': Both CSmith and our own https://github.com/jmid/efftester take the conservative choice of generating programs that are guaranteed to be free of undefined behaviour (as far as I understand).

In a "QuickCheck-family framework" one can also `assume` things about the generated inputs (parity, sortedness, ...) but as the invariant becomes stronger both the generator and the shrinker will shoot more and more in the dark. Rather than 'reduce-and-check' in the shrinker this also motivates a more clever algorithm such as @DRMacIver's. For the generators it motivates the need for a more expressible sub-language of generators.

> It's probably more accurate to say in this terminology that TSTL is a single dedicated generator, reducer, and validity oracle for TSTL programs - the shrinking is "external" but that doesn't matter because you can't write new generators, so you never need to write a new shrinker.

Paraphrasing @DRMacIver, I think a significant difference between some of these systems is that QuickCheck-family frameworks favor an *embedded domain-specific language* (EDSL) for generators: besides the basic generators of `int`s, `char`s, `string`s, etc., they typically come with reusable `tuple`, `list`, `array`, ... generators for generating composite data as well as `oneof`, `map`, `bind`, ... etc. for further composing and refining them. In the presence of these building blocks it is harder to shrink to only 'smaller examples also producable by the same generator".

I think it could therefore help to clarify things if we add a column with **expressive generator EDSL** and let **integrated shrinking** denote whether reduction preserves the invariants expressed in the generator EDSL. That way, frameworks with a less expressive generator EDSL can be marked as such, but still be marked with integrated shrinking. Simultaneously I would add a **Coverage-guiding**-column to signal whether generators (and shrinkers) take coverage into account. Interestingly Crowbar https://github.com/stedolan/crowbar does both the above.

**Comment by agroce** [comment]
DeepState's not hypothesis-level, but includes a good deal more than just base types; it also includes some approaches beyond "guess and check" since ASSUME is just one tool in the kit (and there is assigning-assume, which is search, not guess-n-check).  The real difference is probably that C/C++ types are such that more work is always going to be on the user side; there's too little of a standard "list/tuple" etc., though by using "OneOf" over lambdas plus imperative construction, you definitely get some smart/composed shrinking.

**Comment by agroce** [comment]
but yeah, Echidna/TSTL would both be no for expressive EDSL, yes to integrated shrinking

**Comment by agroce** [comment]
The other reason DeepState's probably got at least a decent EDSL but is missing some obvious options is that some of what you'd need a good generator language for is done in C/C++ by just saying "here's the size, all byte contents are valid items of the type, so we generate by blasting in some bytes" which would not work in saner languages.  :)

**Comment by jmid** [comment]
OK. Since the generator EDSLs for DeepState (and theft) are more limited compared to, e.g., https://github.com/emil-e/rapidcheck/blob/master/doc/generators.md#arbitrary - I've therefore marked them with parens.
I'm hoping you find it reasonable.

**Pull request merged**
